### ISSUE TITLE
Adopting this project

### ISSUE THREAD

**Issue by robinrodricks** [JavascriptNet/Javascript.Net#111]
Hi, this is a great project!

Since it appears you don't find much free time to maintain this project, I would like to propose my adoption of this project.

I will maintain it and publish a nuget and review/merge PRs as needed.

If you are willing to do this, please reach out to me at robinrodricks7 at gmail dot com.

Thank you very much!

**Comment by Ablu** [comment]
Hi!

The project is hosted under a neutral organization already. We can add people there. I know that at least @spahnke is using this and is active.

Personally, I no longer use .NET and do not care too much. But I think a project marines by multiple people has better chances of survival compared to a single owner.

**Comment by robinrodricks** [comment]
How is anyone active? There are old PRs going way back into March with no one bothered to look at it.

https://github.com/JavascriptNet/Javascript.Net/pulls

**Comment by Ablu** [comment]
> How is anyone active? There are old PRs going way back into March with no one bothered to look at it.

I just merged the two that were pending. Feel free to ping people if you think something is stuck. CLR seems to be pretty much legacy tech. So this is slow moving.



> Also the readme still says "Nuget in progress". Its not rocket science to publish a nuget.

Probably @spahnke could comment on how to coordinate that.

**Comment by robinrodricks** [comment]
Ok great.

**Comment by spahnke** [comment]
Sorry, I can't do anything here. I'm a) only a user, not the owner and b) have only limited time. Happy to contribute engine updates and fixes for stuff we find in production, but that's all I have time and energy for, unfortunately. With this project building from source was always our go to way of using the library, especially because we need some non-standard stuff because of legacy reasons that can't be contributed anyway. Regarding engine updates this projects depends on another Nuget package for V8 builds that is also slow moving. So no surprise there. The last update was just last month. I have an update to the newest V8 version ready, but didn't create a PR yet because the other ones weren't merged still and this depends on the previous update being merged. And especially for engine updates I'm waiting for approvals by the repo owner.

Decisions such as this issue need to be made by @oliverbock

**Comment by Ablu** [comment]
Sounds like it would help if we just add @robinrodricks. If we do not get enough reviewers to keep things rolling, then we may need to consider just archiving it to let some fork take over?

CLR seems pretty legacy to me anyway, so maybe time for someone to set up with proper native bindings.

**Comment by robinrodricks** [comment]
I see thanks for your comments both @spahnke  and @Ablu.

It seems to me that there are complexities that do not allow for an easy nuget package. So lets leave it for now.

**Comment by oliverbock** [comment]
I am still interested in and use this project, though I have not had time/priority to do anything for a long time.  I will likely have more time in the next year or two.
