### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by Uncreal** [JavascriptNet/Javascript.Net#90]
Hello,

we using Javascript.net in our ASP.NET Web Applications.
It works good but regularly get errors in our Server log.

error modul  v8.dll

System.AccessViolationException
   at <Module>.v8.Locker.Initialize(v8.Locker*, v8.Isolate*)
   at Noesis.Javascript.JavascriptContext.Enter(Noesis.Javascript.JavascriptContext ByRef)
   at Noesis.Javascript.JavascriptFunction.~JavascriptFunction()
   at Noesis.Javascript.JavascriptFunction.Dispose(Boolean)
   at Noesis.Javascript.JavascriptFunction.Dispose()
   at Noesis.Javascript.JavascriptFunction.Dispose(Boolean)

looks like there is something wrong with the dispose.

maybe someone got an idea. =)

thx

**Comment by spahnke** [comment]
We cannot use the library directly because we had to implement some assumptions for compatibility reasons with our previous engine, that we can't contribute to a general purpose engine. So we maintain our own fork and try to contribute everything we can back to this project. That said, I found a commit we have integrated in our fork that we never contributed, where we removed the finalizer because we hit the same problem. Either I just forgot to do that or I refrained from doing so because I couldn't reproduce the problem reliably.

This is the commit https://github.com/spahnke/Javascript.Net/commit/08d3921026d6e6682309f9340c5313680a347e1b

Are you able to build the library with the above patch applied yourself and can test if that mitigates the problem? If yes, I can submit a PR as soon as you have confirmed that it solves your problem.

**Comment by Uncreal** [comment]
Thank you!
I will try your solution. 
I will report back tomorrow if the issue is resolved.

**Comment by Uncreal** [comment]
@spahnke i can confirm this error is gone with your changes.
Thank you!

**Comment by spahnke** [comment]
Thanks for confirming! I created PR #92 for this.
