### ISSUE TITLE
UnauthorizedAccessException when trying to open a mutex

### ISSUE THREAD

**Issue by Uncreal** [JavascriptNet/Javascript.Net#91]
we using IIS with many different application pools all using application pool identity.
we sometimes get this error:

[UnauthorizedAccessException: Access to the path "FA12B681-E968-4D3A-833D-43B25865BEF1" is denied.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +435
   System.Threading.MutexTryCodeHelper.MutexTryCode(Object userData) +311
   System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) +0
   System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs) +237
   System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity) +266
   System.Threading.Mutex..ctor(Boolean initiallyOwned, String name) +55
   Noesis.Javascript.JavascriptContext..cctor() +80

[typeinitializationexception the type initializer for "Noesis.Javascript.JavascriptContext" threw an exception.]    Noesis.Javascript.JavascriptContext..ctor() +0
--

Do i need to create a new AppDomain for every create instance of JavaScript.Net or how i prevent this exception from happening?

**Comment by spahnke** [comment]
> Do i need to create a new AppDomain for every create instance of JavaScript.Net
No.

I know that we contributed two PRs when we started using this library with the IIS. The first was #53 which made it possible to use different app domains (tests, IIS), without repeated initialization. The second one was #54 which made the initialization thread-safe. The comment of that PR states that we were forced to use a system-wide mutex because of C++/CLI, or more specific CLR restrictions, although an in-process lock would have been sufficient. We don't need a lock over multple processes, but that was our design limitation we hit. It seems that your app pools might be starting at the time triggering a race-condition with the named mutex here (the name is fixed).

Maybe @Ablu can clarify and help here? I'm not super familiar with that code.

Would it be possible to generate a GUID for the named mutex here instead of using a fixed one?

**Comment by Ablu** [comment]
Well 1. std::mutex does not work (IIRC it simply is not available) and 2. we cannot use CLR based techniques, since those are then separated by AppDomains... So this was the simplest workaround for now. But the lock is only hold a very short time, so does this cause any issues?

**Comment by Ablu** [comment]
Ah... I just realized that this message means that the mutex is hit... My testing did not raise an exception, but simply blocked until the mutex was available... I do not really think that generating a GUID every time will help here, since the problem will likely stay. The code has to block here after all...

**Comment by Uncreal** [comment]
@spahnke Yes the problem appears on pool recycle. We got many sites in each pool with a pool by pool recycle were every pool got a different recicle time. On release i always recycle all the pools at the same time. 
If i have traffic in release time i will get a lot of broken sites with this error. 

Maybe i will try it with a generated GUID tomorrow... its worth a shot..

**Comment by oliverbock** [comment]
@Uncreal, you may need to build from source to get the latest changes.

**Comment by Uncreal** [comment]
@oliverbock i am on the latest.
Im running it with a unnamed mutex now and i think the errors are gone.

`System::Threading::Mutex mutex(true);`

but i have no idea what this change means for the rest of the code.
